[package]
name = "rpgmaker-save-editor"
version = "0.2.1"
description = "Cross-platform save editor for RPG Maker"
authors = ["JJayRex"]
edition = "2024"


[lib]
name = "rpgmaker_save_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rpgsave = { path = "../crates/rpgsave" }
rpgsave-protocol = { path = "../crates/protocol" }

[dev-dependencies]
tauri = { version = "2", features = ["test"] }
